import type { DanceDifficulty, DanceMovementType } from '../types';

/** Raw move catalog — World Dance Heritage reference (Raqs Sharqi glossary). */
export type BellyDanceMoveSeed = {
	id: string;
	name: string;
	cue: string;
	danceCat: string;
	focus: string[];
	movementType: DanceMovementType;
	difficulty: DanceDifficulty;
};

export const bellyDanceMoveSeeds: BellyDanceMoveSeed[] = [
	{
		id: 'bd-arabesque',
		name: 'Arabesque',
		cue: 'A travelling step with a pivot on one foot and an extended leg',
		danceCat: 'Travelling Steps',
		focus: ['full-body'],
		movementType: 'sharp',
		difficulty: 'intermediate',
	},
	{
		id: 'bd-backbend',
		name: 'Backbend',
		cue: 'Leaning backwards with the upper body',
		danceCat: 'Undulation',
		focus: ['full-body', 'core'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-barrel-turn',
		name: 'Barrel Turn',
		cue: 'Similar to the corkscrew turn, but with the arms extended (one upwards and the other downwards)',
		danceCat: 'Turns',
		focus: ['full-body'],
		movementType: 'sharp',
		difficulty: 'intermediate',
	},
	{
		id: 'bd-belly-flutters',
		name: 'Belly Flutters',
		cue: 'Quick contractions and releases of the upper abdominal muscles',
		danceCat: 'Lifts & Drops',
		focus: ['abdomen', 'core'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-belly-pop',
		name: 'Belly Pop',
		cue: 'A quick contraction and release of the lower abdominal muscles',
		danceCat: 'Lifts & Drops',
		focus: ['abdomen', 'core'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-camel',
		name: 'Camel',
		cue: 'An isolated torso undulation like a wave, forward and back. In the Egyptian style, it is confined mostly to the lower abdomen and lower back',
		danceCat: 'Undulation',
		focus: ['core', 'abdomen'],
		movementType: 'smooth',
		difficulty: 'beginner',
	},
	{
		id: 'bd-chest-circle',
		name: 'Chest Circle',
		cue: 'A circular movement of the ribcage, on the horizontal plane (but it can sometimes be on the vertical plane)',
		danceCat: 'Circles',
		focus: ['chest'],
		movementType: 'smooth',
		difficulty: 'beginner',
	},
	{
		id: 'bd-chest-drop',
		name: 'Chest Drop',
		cue: 'An isolated movement of the ribcage downwards',
		danceCat: 'Lifts & Drops',
		focus: ['chest'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-chest-lift',
		name: 'Chest Lift',
		cue: 'An isolated movement of the ribcage upwards',
		danceCat: 'Lifts & Drops',
		focus: ['chest'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-chest-slide',
		name: 'Chest Slide',
		cue: 'Moving the chest from side-to-side, keeping it level',
		danceCat: 'Slides',
		focus: ['chest'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-choo-choo-shimmy',
		name: 'Choo Choo Shimmies',
		cue: 'Hip shimmies performed on relevé, while shuffling along the dance floor',
		danceCat: 'Shimmies',
		focus: ['hips', 'legs'],
		movementType: 'sharp',
		difficulty: 'intermediate',
	},
	{
		id: 'bd-corkscrew-turn',
		name: 'Corkscrew Turn',
		cue: 'A turn performed on the spot, by crossing one foot in front of the other and pivoting on the heel of the foot that is in front',
		danceCat: 'Turns',
		focus: ['full-body'],
		movementType: 'sharp',
		difficulty: 'intermediate',
	},
	{
		id: 'bd-egyptian-walk',
		name: 'Egyptian Walk (Hagalla)',
		cue: 'Stepping down on one foot at a time, whilst lowering the corresponding hip',
		danceCat: 'Travelling Steps',
		focus: ['hips', 'legs'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-figure-8-horizontal',
		name: 'Figure of Eight (Hip Horizontal)',
		cue: 'Tracing a figure of eight, or infinity symbol pattern, with the hips on a horizontal plane',
		danceCat: 'Figure 8s',
		focus: ['hips'],
		movementType: 'smooth',
		difficulty: 'intermediate',
	},
	{
		id: 'bd-figure-8-vertical',
		name: 'Figure of Eight (Hip Vertical)',
		cue: 'Tracing a figure of eight, or infinity symbol pattern, with the hips on a vertical plane, going inwards, towards the centre of the body',
		danceCat: 'Figure 8s',
		focus: ['hips'],
		movementType: 'smooth',
		difficulty: 'intermediate',
	},
	{
		id: 'bd-floorwork',
		name: 'Floorwork',
		cue: 'Dancing movements done while sitting or lying on the floor',
		danceCat: 'Floor Work',
		focus: ['full-body'],
		movementType: 'variable',
		difficulty: 'intermediate',
	},
	{
		id: 'bd-grapevine',
		name: 'Grapevine',
		cue: 'A sideways travelling movement with sidesteps and steps across the support foot',
		danceCat: 'Travelling Steps',
		focus: ['legs'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-head-slide',
		name: 'Head Slide',
		cue: 'A horizontal sliding movement of the head side to side',
		danceCat: 'Head',
		focus: ['head'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-heels-stomp',
		name: 'Heels Stomp',
		cue: 'Tapping both heels flat to stress a downward accent in the music',
		danceCat: 'Feet',
		focus: ['feet'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-hip-bump',
		name: 'Hip Bump',
		cue: 'A thrusting movement of the hip to the side with emphasis',
		danceCat: 'Lifts & Drops',
		focus: ['hips'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-hip-circle',
		name: 'Hip Circle',
		cue: 'A circular movement of the hips, on a horizontal plane',
		danceCat: 'Circles',
		focus: ['hips'],
		movementType: 'smooth',
		difficulty: 'beginner',
	},
	{
		id: 'bd-hip-drop',
		name: 'Hip Drop',
		cue: 'A movement of one hip up to down, with emphasis on the downward motion. Only one hip moves and no weight is placed on the corresponding hip',
		danceCat: 'Lifts & Drops',
		focus: ['hips'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-hip-jewel',
		name: 'Hip Jewel',
		cue: 'Half horizontal figures of eight of one hip, punctuated at the end by a small abdominal contraction, with a ripple effect',
		danceCat: 'Figure 8s',
		focus: ['hips', 'abdomen'],
		movementType: 'smooth',
		difficulty: 'advanced',
	},
	{
		id: 'bd-hip-lift',
		name: 'Hip Lift',
		cue: 'A movement of one hip at a time down to up, with emphasis on the upward motion',
		danceCat: 'Lifts & Drops',
		focus: ['hips'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-hip-shimmy',
		name: 'Hip Shimmy',
		cue: 'Bending and straightening the knees one at a time very fast, making the hips vibrate up and down and the torso wobble',
		danceCat: 'Shimmies',
		focus: ['hips'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-hip-slide',
		name: 'Hip Slide',
		cue: 'A horizontal sliding movement of the hips from side to side',
		danceCat: 'Slides',
		focus: ['hips'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-hip-tak',
		name: 'Hip Tak',
		cue: 'A small and sharp hip movement that creates an accent, similar to a hip bump',
		danceCat: 'Lifts & Drops',
		focus: ['hips'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-hip-twist',
		name: 'Hip Twist',
		cue: 'Moving one hip forward and the other back, on a horizontal plane',
		danceCat: 'Twists',
		focus: ['hips'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-layering',
		name: 'Layering',
		cue: 'Performing two movements of the same part of the body at the same time (e.g., a hip figure of eight while shimming the hips)',
		danceCat: 'Technique',
		focus: ['full-body'],
		movementType: 'variable',
		difficulty: 'advanced',
	},
	{
		id: 'bd-maya',
		name: 'Maya',
		cue: 'Like a hip vertical figure of eight, but with the hips moving outwards, away from the centre of the body',
		danceCat: 'Figure 8s',
		focus: ['hips'],
		movementType: 'smooth',
		difficulty: 'intermediate',
	},
	{
		id: 'bd-pelvic-lift-drop',
		name: 'Pelvic Lift and Drop',
		cue: 'An isolated movement of the pelvis upwards and downward, with the accent on the down movement',
		danceCat: 'Lifts & Drops',
		focus: ['pelvis'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-pelvic-tilt',
		name: 'Pelvic Tilt with Weight Transfer',
		cue: 'Tilting the pelvis, with weight transfer between one leg positioned in front and the other leg that is slightly back',
		danceCat: 'Pelvis',
		focus: ['pelvis', 'legs'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-releve',
		name: 'Relevé (Demi-pointe)',
		cue: 'A movement in which the dancer rises on the tips of the toes',
		danceCat: 'Feet',
		focus: ['feet', 'legs'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-scissor-step',
		name: 'Scissor Step',
		cue: 'Stepping with the same foot forward and back, while the other foot steps on the spot',
		danceCat: 'Travelling Steps',
		focus: ['legs'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-shoulder-rolls',
		name: 'Shoulder Rolls',
		cue: 'Alternating rolling movements of the shoulders',
		danceCat: 'Shoulders',
		focus: ['shoulders'],
		movementType: 'smooth',
		difficulty: 'beginner',
	},
	{
		id: 'bd-shoulder-shimmy',
		name: 'Shoulder Shimmies',
		cue: 'Vibration of the shoulders, achieved by moving them in quick alternation back and forward',
		danceCat: 'Shimmies',
		focus: ['shoulders'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-shoulder-twist',
		name: 'Shoulder Twist',
		cue: 'Twisting the torso so one shoulder moves forward at a time, keeping the centre of the chest stationary',
		danceCat: 'Twists',
		focus: ['shoulders', 'chest'],
		movementType: 'sharp',
		difficulty: 'beginner',
	},
	{
		id: 'bd-snake-arms',
		name: 'Snake Arms',
		cue: 'Moving the arm joints in smooth succession from the shoulder to the elbow and wrist, with a wave or snake-like effect',
		danceCat: 'Arms',
		focus: ['arms'],
		movementType: 'smooth',
		difficulty: 'beginner',
	},
	{
		id: 'bd-soheir-zaki-drop',
		name: 'Soheir Zaki Hip-Drop',
		cue: 'A movement of one hip at a time up to down, with emphasis on the downward motion. The hips move in succession, one at a time and the dancer stands on tiptoes',
		danceCat: 'Lifts & Drops',
		focus: ['hips', 'feet'],
		movementType: 'sharp',
		difficulty: 'intermediate',
	},
];
