import type { CatalogDifficulty, ExerciseType, ItemCat, WeightUnit } from '../types';

export type StrengthExerciseSeed = {
	id: string;
	name: string;
	cue: string;
	cat: ItemCat;
	muscles: string;
	exerciseType: ExerciseType;
	equipment: string[];
	difficulty: CatalogDifficulty;
	unit: WeightUnit;
	defaultSets: number;
	defaultReps: string;
	weightIncrement?: number;
};

export const strengthExerciseSeeds: StrengthExerciseSeed[] = [
	// ── CHEST ────────────────────────────────────────────────────────
	{
		id: 'st-bb-bench-press',
		name: 'Barbell Bench Press',
		cue: 'Foundation pressing movement; incline and decline variations available',
		cat: 'Chest',
		muscles: 'Chest · Triceps · Anterior delts',
		exerciseType: 'compound',
		equipment: ['Barbell', 'Bench'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-db-bench-press',
		name: 'Dumbbell Bench Press',
		cue: 'Greater range of motion than barbell',
		cat: 'Chest',
		muscles: 'Chest · Triceps · Anterior delts',
		exerciseType: 'compound',
		equipment: ['Dumbbells', 'Bench'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-incline-bb-bench',
		name: 'Incline Barbell Bench Press',
		cue: 'Targets upper chest more effectively',
		cat: 'Chest',
		muscles: 'Upper chest · Anterior delts · Triceps',
		exerciseType: 'compound',
		equipment: ['Barbell', 'Incline bench'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-incline-db-bench',
		name: 'Incline Dumbbell Bench Press',
		cue: 'Increased range of motion at incline',
		cat: 'Chest',
		muscles: 'Upper chest · Anterior delts · Triceps',
		exerciseType: 'compound',
		equipment: ['Dumbbells', 'Incline bench'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-weighted-dips-chest',
		name: 'Weighted Dips (Chest)',
		cue: 'Lean forward for chest emphasis; unweighted as modification',
		cat: 'Chest',
		muscles: 'Chest · Triceps · Anterior delts',
		exerciseType: 'compound',
		equipment: ['Dip station', 'Weight belt'],
		difficulty: 'advanced',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-decline-bench',
		name: 'Decline Bench Press',
		cue: 'Targets lower chest; less common variation',
		cat: 'Chest',
		muscles: 'Lower chest · Triceps · Anterior delts',
		exerciseType: 'compound',
		equipment: ['Barbell', 'Decline bench'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-push-ups',
		name: 'Push-Ups',
		cue: 'Excellent home alternative; many variations',
		cat: 'Chest',
		muscles: 'Chest · Triceps · Anterior delts · Core',
		exerciseType: 'compound',
		equipment: ['Bodyweight'],
		difficulty: 'beginner',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '12',
	},
	{
		id: 'st-cable-chest-fly',
		name: 'Cable Chest Flies',
		cue: 'Great for chest pump and stretch',
		cat: 'Chest',
		muscles: 'Chest · Anterior delts',
		exerciseType: 'isolation',
		equipment: ['Cable machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-pec-deck',
		name: 'Pec Deck Machine',
		cue: 'Controlled, machine-based chest isolation',
		cat: 'Chest',
		muscles: 'Chest · Anterior delts',
		exerciseType: 'isolation',
		equipment: ['Pec deck machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-db-pullover',
		name: 'Dumbbell Pullover',
		cue: 'Also targets back and core',
		cat: 'Chest',
		muscles: 'Chest · Lats · Core',
		exerciseType: 'isolation',
		equipment: ['Dumbbell', 'Bench'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	// ── BACK ─────────────────────────────────────────────────────────
	{
		id: 'st-bb-deadlift',
		name: 'Barbell Deadlift',
		cue: 'King of compound lifts; high technical demand',
		cat: 'Back',
		muscles: 'Lower back · Glutes · Hamstrings · Quads · Traps',
		exerciseType: 'compound',
		equipment: ['Barbell'],
		difficulty: 'advanced',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '5',
		weightIncrement: 5,
	},
	{
		id: 'st-bb-bent-over-row',
		name: 'Bent-Over Barbell Row',
		cue: 'Horizontal pulling pattern; essential back builder',
		cat: 'Back',
		muscles: 'Lats · Rhomboids · Biceps · Traps · Rear delts',
		exerciseType: 'compound',
		equipment: ['Barbell'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-weighted-pull-up',
		name: 'Weighted Pull-Ups',
		cue: 'Unweighted pull-ups are beginner alternative',
		cat: 'Back',
		muscles: 'Lats · Biceps · Rear delts',
		exerciseType: 'compound',
		equipment: ['Pull-up bar', 'Weight belt'],
		difficulty: 'advanced',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '6',
		weightIncrement: 5,
	},
	{
		id: 'st-wide-pull-up',
		name: 'Wide-Grip Pull-Up',
		cue: 'Wider grip emphasizes lat stretch',
		cat: 'Back',
		muscles: 'Lats · Biceps · Rear delts',
		exerciseType: 'compound',
		equipment: ['Pull-up bar'],
		difficulty: 'intermediate',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '6',
	},
	{
		id: 'st-close-pull-up',
		name: 'Close-Grip Pull-Up',
		cue: 'Closer grip increases bicep involvement',
		cat: 'Back',
		muscles: 'Lats · Biceps · Rear delts',
		exerciseType: 'compound',
		equipment: ['Pull-up bar'],
		difficulty: 'intermediate',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '6',
	},
	{
		id: 'st-t-bar-row',
		name: 'Standing T-Bar Row',
		cue: 'Alternative to bent-over rows',
		cat: 'Back',
		muscles: 'Lats · Rhomboids · Biceps · Traps',
		exerciseType: 'compound',
		equipment: ['T-bar or landmine'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-lat-pulldown-wide',
		name: 'Lat Pulldown (Wide-Grip)',
		cue: 'Great pull-up alternative',
		cat: 'Back',
		muscles: 'Lats · Biceps · Rear delts',
		exerciseType: 'compound',
		equipment: ['Cable machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 5,
	},
	{
		id: 'st-lat-pulldown-close',
		name: 'Lat Pulldown (Close-Grip)',
		cue: 'More bicep emphasis than wide-grip',
		cat: 'Back',
		muscles: 'Lats · Biceps · Rear delts',
		exerciseType: 'compound',
		equipment: ['Cable machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 5,
	},
	{
		id: 'st-seated-cable-row',
		name: 'Seated Cable Row',
		cue: 'Controlled horizontal pulling; good form learning',
		cat: 'Back',
		muscles: 'Lats · Rhomboids · Biceps · Traps',
		exerciseType: 'compound',
		equipment: ['Cable machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 5,
	},
	{
		id: 'st-straight-arm-pulldown',
		name: 'Straight-Arm Pulldown',
		cue: 'Unique lat isolation with excellent stretch',
		cat: 'Back',
		muscles: 'Lats · Core',
		exerciseType: 'isolation',
		equipment: ['Cable machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-reverse-fly-machine',
		name: 'Reverse Fly Machine',
		cue: 'Isolated rear delt and back work',
		cat: 'Back',
		muscles: 'Rear delts · Back',
		exerciseType: 'isolation',
		equipment: ['Machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-pendlay-row',
		name: 'Barbell Rows (Pendlay)',
		cue: 'Chest-supported version of bent-over row',
		cat: 'Back',
		muscles: 'Lats · Rhomboids · Biceps · Traps · Rear delts',
		exerciseType: 'compound',
		equipment: ['Barbell', 'Bench'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-machine-row',
		name: 'Machine Row (Chest-Supported)',
		cue: 'Safer, controlled version of barbell row',
		cat: 'Back',
		muscles: 'Lats · Rhomboids · Biceps · Traps',
		exerciseType: 'compound',
		equipment: ['Machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 5,
	},
	// ── SHOULDERS ────────────────────────────────────────────────────
	{
		id: 'st-bb-ohp',
		name: 'Barbell Overhead Press',
		cue: 'Fundamental pressing pattern; seated or standing',
		cat: 'Shoulders',
		muscles: 'Front & medial delts · Triceps · Upper chest · Core',
		exerciseType: 'compound',
		equipment: ['Barbell'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-db-ohp',
		name: 'Dumbbell Overhead Press',
		cue: 'Greater range of motion than barbell',
		cat: 'Shoulders',
		muscles: 'Shoulders · Triceps · Upper chest · Core',
		exerciseType: 'compound',
		equipment: ['Dumbbells'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 5,
	},
	{
		id: 'st-arnold-press',
		name: 'Arnold Press',
		cue: '360-degree shoulder movement; excellent for all delts',
		cat: 'Shoulders',
		muscles: 'Shoulders · Triceps · Upper chest',
		exerciseType: 'compound',
		equipment: ['Dumbbells'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 5,
	},
	{
		id: 'st-lateral-raise',
		name: 'Lateral Raise',
		cue: 'Primary shoulder width builder',
		cat: 'Shoulders',
		muscles: 'Medial delts · Anterior delts',
		exerciseType: 'isolation',
		equipment: ['Dumbbells or cable'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-front-raise',
		name: 'Front Dumbbell Raise',
		cue: 'Targets front shoulders; often overused',
		cat: 'Shoulders',
		muscles: 'Anterior delts · Medial delts',
		exerciseType: 'isolation',
		equipment: ['Dumbbells'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-rear-delt-fly-machine',
		name: 'Rear Delt Fly (Pec Deck)',
		cue: 'Shoulder balance and posture correction',
		cat: 'Shoulders',
		muscles: 'Rear delts · Back',
		exerciseType: 'isolation',
		equipment: ['Pec deck machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '15',
		weightIncrement: 2.5,
	},
	{
		id: 'st-face-pull',
		name: 'Face Pulls',
		cue: 'Excellent for shoulder health and posture',
		cat: 'Shoulders',
		muscles: 'Rear delts · Traps',
		exerciseType: 'isolation',
		equipment: ['Cable machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '15',
		weightIncrement: 2.5,
	},
	{
		id: 'st-bent-over-reverse-fly',
		name: 'Bent-Over Reverse Fly',
		cue: 'Alternative rear delt movement',
		cat: 'Shoulders',
		muscles: 'Rear delts · Back',
		exerciseType: 'isolation',
		equipment: ['Dumbbells'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-handstand-push-up',
		name: 'Handstand Push-Ups',
		cue: 'Bodyweight shoulder pressing alternative',
		cat: 'Shoulders',
		muscles: 'Shoulders · Triceps · Core',
		exerciseType: 'compound',
		equipment: ['Bodyweight'],
		difficulty: 'advanced',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '6',
	},
	// ── BICEPS ───────────────────────────────────────────────────────
	{
		id: 'st-bb-curl',
		name: 'Barbell Curl',
		cue: 'Fundamental bicep builder',
		cat: 'Biceps',
		muscles: 'Biceps · Forearms',
		exerciseType: 'isolation',
		equipment: ['Barbell'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 2.5,
	},
	{
		id: 'st-db-curl',
		name: 'Dumbbell Curl',
		cue: 'Greater range of motion than barbell',
		cat: 'Biceps',
		muscles: 'Biceps · Forearms',
		exerciseType: 'isolation',
		equipment: ['Dumbbells'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 2.5,
	},
	{
		id: 'st-hammer-curl',
		name: 'Hammer Curl',
		cue: 'Neutral grip targets brachialis',
		cat: 'Biceps',
		muscles: 'Biceps · Forearms · Brachialis',
		exerciseType: 'isolation',
		equipment: ['Dumbbells'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 2.5,
	},
	{
		id: 'st-preacher-curl',
		name: 'Preacher Curl',
		cue: 'Eliminates momentum; strict isolation',
		cat: 'Biceps',
		muscles: 'Biceps · Forearms',
		exerciseType: 'isolation',
		equipment: ['Preacher bench', 'Barbell or dumbbells'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 2.5,
	},
	{
		id: 'st-concentration-curl',
		name: 'Concentration Curl',
		cue: 'Single-arm isolation; minimal momentum',
		cat: 'Biceps',
		muscles: 'Biceps · Forearms',
		exerciseType: 'isolation',
		equipment: ['Dumbbell'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10 ea',
		weightIncrement: 2.5,
	},
	{
		id: 'st-ez-bar-curl',
		name: 'Barbell Curl (EZ-Bar)',
		cue: 'Reduces wrist strain compared to straight bar',
		cat: 'Biceps',
		muscles: 'Biceps · Forearms',
		exerciseType: 'isolation',
		equipment: ['EZ-bar'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 2.5,
	},
	{
		id: 'st-cable-curl',
		name: 'Cable Curl',
		cue: 'Constant tension throughout movement',
		cat: 'Biceps',
		muscles: 'Biceps · Forearms',
		exerciseType: 'isolation',
		equipment: ['Cable machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-chin-up',
		name: 'Chin-Ups',
		cue: 'Hybrid bicep and back movement',
		cat: 'Biceps',
		muscles: 'Biceps · Lats · Rear delts',
		exerciseType: 'compound',
		equipment: ['Pull-up bar'],
		difficulty: 'intermediate',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '6',
	},
	// ── TRICEPS ──────────────────────────────────────────────────────
	{
		id: 'st-tricep-dip',
		name: 'Tricep Dips',
		cue: 'Bodyweight tricep compound; stay upright for tricep focus',
		cat: 'Triceps',
		muscles: 'Triceps · Chest · Anterior delts',
		exerciseType: 'compound',
		equipment: ['Dip station'],
		difficulty: 'beginner',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '10',
	},
	{
		id: 'st-tricep-rope-pushdown',
		name: 'Tricep Rope Pushdown',
		cue: 'Primary tricep isolation; adjustable resistance',
		cat: 'Triceps',
		muscles: 'Triceps · Anterior delts',
		exerciseType: 'isolation',
		equipment: ['Cable machine', 'Rope'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-tricep-bar-pushdown',
		name: 'Tricep Pushdown (Straight Bar)',
		cue: 'Similar to rope but different hand position',
		cat: 'Triceps',
		muscles: 'Triceps · Anterior delts',
		exerciseType: 'isolation',
		equipment: ['Cable machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-tricep-overhead-extension',
		name: 'Tricep Rope Extension (Overhead)',
		cue: 'Vertical tricep isolation; excellent stretch',
		cat: 'Triceps',
		muscles: 'Triceps · Shoulders',
		exerciseType: 'isolation',
		equipment: ['Cable machine', 'Rope'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-db-tricep-extension',
		name: 'Dumbbell Tricep Extension',
		cue: 'Seated or standing',
		cat: 'Triceps',
		muscles: 'Triceps · Shoulders',
		exerciseType: 'isolation',
		equipment: ['Dumbbell', 'Bench'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 2.5,
	},
	{
		id: 'st-tricep-kickback',
		name: 'Tricep Kickback',
		cue: 'Single-arm isolation; lightweight appropriate',
		cat: 'Triceps',
		muscles: 'Triceps · Anterior delts',
		exerciseType: 'isolation',
		equipment: ['Dumbbell'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12 ea',
		weightIncrement: 2.5,
	},
	// ── LEGS ─────────────────────────────────────────────────────────
	{
		id: 'st-bb-squat',
		name: 'Barbell Squat',
		cue: 'Fundamental lower body pattern; high or low bar variation',
		cat: 'Legs',
		muscles: 'Quads · Glutes · Hamstrings · Lower back · Core',
		exerciseType: 'compound',
		equipment: ['Barbell', 'Squat rack'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-front-squat',
		name: 'Front Squat',
		cue: 'Forward position increases quad emphasis',
		cat: 'Legs',
		muscles: 'Quads · Glutes · Hamstrings · Core',
		exerciseType: 'compound',
		equipment: ['Barbell', 'Squat rack'],
		difficulty: 'advanced',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '6',
		weightIncrement: 5,
	},
	{
		id: 'st-goblet-squat',
		name: 'Goblet Squat',
		cue: 'Excellent form-learning variation',
		cat: 'Legs',
		muscles: 'Quads · Glutes · Hamstrings · Core',
		exerciseType: 'compound',
		equipment: ['Dumbbell or kettlebell'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 5,
	},
	{
		id: 'st-leg-press',
		name: 'Leg Press',
		cue: 'Machine-based leg press; reduced technical demand',
		cat: 'Legs',
		muscles: 'Quads · Glutes · Hamstrings · Adductors',
		exerciseType: 'compound',
		equipment: ['Leg press machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '10',
		weightIncrement: 10,
	},
	{
		id: 'st-split-squat',
		name: 'Split Squat',
		cue: 'Unilateral leg work; addresses imbalances',
		cat: 'Legs',
		muscles: 'Quads · Glutes · Hamstrings · Hip flexors',
		exerciseType: 'compound',
		equipment: ['Dumbbells or barbell'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10 ea',
		weightIncrement: 5,
	},
	{
		id: 'st-bulgarian-split-squat',
		name: 'Bulgarian Split Squat',
		cue: 'Elevated rear leg increases difficulty',
		cat: 'Legs',
		muscles: 'Quads · Glutes · Hamstrings · Hip flexors · Core',
		exerciseType: 'compound',
		equipment: ['Bench', 'Dumbbells'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10 ea',
		weightIncrement: 5,
	},
	{
		id: 'st-leg-extension',
		name: 'Leg Extension',
		cue: 'Pure quad isolation; machine-based',
		cat: 'Legs',
		muscles: 'Quads',
		exerciseType: 'isolation',
		equipment: ['Leg extension machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-rdl',
		name: 'Romanian Deadlift',
		cue: 'Hip hinge emphasis; less knee bend than conventional deadlift',
		cat: 'Legs',
		muscles: 'Hamstrings · Lower back · Glutes · Traps',
		exerciseType: 'compound',
		equipment: ['Barbell'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 5,
	},
	{
		id: 'st-leg-curl',
		name: 'Leg Curl',
		cue: 'Pure hamstring isolation',
		cat: 'Legs',
		muscles: 'Hamstrings',
		exerciseType: 'isolation',
		equipment: ['Leg curl machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-nordic-curl',
		name: 'Nordic Hamstring Curl',
		cue: 'Eccentric-focused; bodyweight alternative',
		cat: 'Legs',
		muscles: 'Hamstrings · Lower back · Core',
		exerciseType: 'compound',
		equipment: ['Bench or machine'],
		difficulty: 'advanced',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '6',
	},
	{
		id: 'st-bb-hip-thrust',
		name: 'Barbell Hip Thrust',
		cue: 'Glute-dominant hip extension',
		cat: 'Legs',
		muscles: 'Glutes · Hamstrings · Quads · Lower back',
		exerciseType: 'compound',
		equipment: ['Barbell', 'Bench'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '10',
		weightIncrement: 5,
	},
	{
		id: 'st-machine-hip-thrust',
		name: 'Machine Hip Thrust',
		cue: 'Machine-based hip thrust; easier learning curve',
		cat: 'Legs',
		muscles: 'Glutes · Hamstrings · Quads · Lower back',
		exerciseType: 'compound',
		equipment: ['Hip thrust machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '10',
		weightIncrement: 5,
	},
	{
		id: 'st-walking-lunge',
		name: 'Walking Lunge',
		cue: 'Traveling movement; functional pattern',
		cat: 'Legs',
		muscles: 'Quads · Glutes · Hamstrings · Hip flexors · Core',
		exerciseType: 'compound',
		equipment: ['Dumbbells or barbell'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '12 ea',
		weightIncrement: 5,
	},
	{
		id: 'st-reverse-lunge',
		name: 'Reverse Lunge',
		cue: 'Reduced knee stress compared to forward lunge',
		cat: 'Legs',
		muscles: 'Quads · Glutes · Hamstrings · Core',
		exerciseType: 'compound',
		equipment: ['Dumbbells or barbell'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10 ea',
		weightIncrement: 5,
	},
	{
		id: 'st-lunge-twist',
		name: 'Lunge Twist',
		cue: 'Adds core and rotational component to lunge',
		cat: 'Legs',
		muscles: 'Quads · Glutes · Obliques · Core',
		exerciseType: 'compound',
		equipment: ['Dumbbells or medicine ball'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10 ea',
		weightIncrement: 5,
	},
	{
		id: 'st-standing-calf-raise',
		name: 'Standing Calf Raise',
		cue: 'Primary calf builder — gastrocnemius',
		cat: 'Legs',
		muscles: 'Calves (gastrocnemius) · Soleus',
		exerciseType: 'isolation',
		equipment: ['Barbell or calf raise machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '12',
		weightIncrement: 2.5,
	},
	{
		id: 'st-seated-calf-raise',
		name: 'Seated Calf Raise',
		cue: 'Seated position emphasizes soleus',
		cat: 'Legs',
		muscles: 'Calves (soleus) · Gastrocnemius',
		exerciseType: 'isolation',
		equipment: ['Calf raise machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 4,
		defaultReps: '15',
		weightIncrement: 2.5,
	},
	// ── CORE ─────────────────────────────────────────────────────────
	{
		id: 'st-cable-crunch',
		name: 'Cable Crunch',
		cue: 'Machine-based core isolation',
		cat: 'Core',
		muscles: 'Rectus abdominis · Obliques',
		exerciseType: 'isolation',
		equipment: ['Cable machine'],
		difficulty: 'beginner',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '15',
		weightIncrement: 2.5,
	},
	{
		id: 'st-hanging-knee-raise',
		name: 'Hanging Dumbbell Knee Raise',
		cue: 'Weighted core movement on pull-up bar',
		cat: 'Core',
		muscles: 'Lower abs · Hip flexors · Lats',
		exerciseType: 'compound',
		equipment: ['Pull-up bar', 'Dumbbell'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10',
		weightIncrement: 5,
	},
	{
		id: 'st-captains-chair-raise',
		name: "Captain's Chair Leg Raise",
		cue: 'Isolated core work; controlled movement',
		cat: 'Core',
		muscles: 'Lower abs · Hip flexors · Core',
		exerciseType: 'isolation',
		equipment: ["Captain's chair machine"],
		difficulty: 'beginner',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '12',
	},
	{
		id: 'st-ab-wheel',
		name: 'Ab Wheel Rollout',
		cue: 'Advanced core movement; high difficulty',
		cat: 'Core',
		muscles: 'Rectus abdominis · Transverse abdominis · Shoulders',
		exerciseType: 'isolation',
		equipment: ['Ab wheel'],
		difficulty: 'advanced',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '8',
	},
	{
		id: 'st-landmine-rotation',
		name: 'Landmine Rotation',
		cue: 'Rotational core work with heavy load potential',
		cat: 'Core',
		muscles: 'Obliques · Core · Shoulders',
		exerciseType: 'compound',
		equipment: ['Landmine', 'Barbell'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '10 ea',
		weightIncrement: 5,
	},
	{
		id: 'st-plank',
		name: 'Plank',
		cue: 'Static core engagement; foundational',
		cat: 'Core',
		muscles: 'Rectus abdominis · Transverse abdominis · Shoulders',
		exerciseType: 'isometric',
		equipment: ['Bodyweight'],
		difficulty: 'beginner',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '45 s',
	},
	{
		id: 'st-side-plank',
		name: 'Side Plank',
		cue: 'Unilateral core stability',
		cat: 'Core',
		muscles: 'Obliques · Core · Lateral chain',
		exerciseType: 'isometric',
		equipment: ['Bodyweight'],
		difficulty: 'beginner',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '30 s ea',
	},
	// ── FULL BODY ────────────────────────────────────────────────────
	{
		id: 'st-med-ball-slam',
		name: 'Medicine Ball Slam',
		cue: 'Explosive core and full-body power',
		cat: 'Full Body',
		muscles: 'Core · Shoulders · Chest · Quads',
		exerciseType: 'dynamic',
		equipment: ['Medicine ball'],
		difficulty: 'intermediate',
		unit: 'lb',
		defaultSets: 3,
		defaultReps: '8',
		weightIncrement: 5,
	},
	{
		id: 'st-burpee',
		name: 'Burpees',
		cue: 'Full-body compound with cardio element',
		cat: 'Full Body',
		muscles: 'Chest · Core · Quads · Glutes · Cardiovascular',
		exerciseType: 'compound',
		equipment: ['Bodyweight'],
		difficulty: 'intermediate',
		unit: 'bodyweight',
		defaultSets: 3,
		defaultReps: '10',
	},
];
